### ISSUE TITLE
Setting Voice Assistant Engine

### ISSUE THREAD

**Issue by LordNex** [smkrv/ha-text-ai#3]
Once I got the integration installed and working I expected it would show up as an option to select as a voice assistant engine in the Voice section of Home Assistant. But it doesn’t seem to show up there and only seems accessible via the sensor or by creating an automation to fire off the service. 

Is there a way to pipe the Assist setup through this integration so the primary voice assistant uses it?

**Comment by smkrv** [comment]
@LordNex, Thank you for your suggestion! Currently, the HA Text AI integration is designed to work with text inputs only and doesn't have built-in voice capabilities. It wasn't originally planned to appear as a voice assistant engine option in the Voice section of Home Assistant.

However, you can definitely create a workflow that uses Home Assistant's voice recognition capabilities and then passes the transcribed text to HA Text AI. Here's how you could set this up:

## Using HA Text AI with Voice Commands

You can create an automation that:
1. Listens for voice commands using Home Assistant's built-in voice recognition
2. Sends the transcribed text to HA Text AI
3. Optionally speaks back the response using text-to-speech

### Example Automation

```yaml
alias: "Voice Assistant with HA Text AI"
description: "Process voice commands through HA Text AI"
trigger:
  - platform: event
    event_type: conversation.processing
    event_data:
      language: en  # Adjust for your language
mode: single
action:
  - variables:
      voice_command: "{{ trigger.event.data.text }}"
  - service: ha_text_ai.ask_question
    data:
      instance: your_instance_name
      question: "{{ voice_command }}"
    response_variable: ai_response
  - service: tts.speak
    data:
      entity_id: media_player.your_speaker
      message: "{{ ai_response.response }}"
```

This automation will intercept voice commands processed by Home Assistant, send them to your HA Text AI instance, and then speak the response through your chosen media player.

While full voice assistant integration isn't currently on my roadmap, this community-driven approach allows you to leverage both voice recognition and HA Text AI's capabilities. I'd be interested to hear how this works for you!
